language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV="py27-tests,lint,coverage"
    - python: 3.4
      env: TOXENV="py34-tests,coverage"
    - python: 3.5
      env: TOXENV="py35-tests,coverage"
    - python: 3.6
      env: TOXENV="py36-tests,coverage"

before_install:
  - pip install tox

install:
  - pip install .

script:
  - tox
